### ISSUE TITLE
还有redict问题

### ISSUE THREAD

**Issue by disappearedgod** [xindoo/ershoufang#1]
![image](https://cloud.githubusercontent.com/assets/4340627/26495358/e0634316-4255-11e7-93ce-5138b2b6cc20.png)

**Comment by xindoo** [comment]
数据爬取是没问题的，但有时候会被链家ban，会redirect到验证码的页面。

**Comment by rainn048** [comment]
重定向的问题怎么解决

**Comment by rainn048** [comment]
这个跟代码有关系，从第二页开始，网页从https://bj.lianjia.com/ershoufang/变成https://bj.lianjia.com/ershoufang/pg2/，你只简单提取页码数字，没有加pg，所以导致重定向问题，加上pg就能解决

**Comment by xindoo** [comment]
暂停了每日抓取的定时任务

**Comment by disappearedgod** [comment]
链家的redirect 验证码破解有思路不，想试试

________________________________
xuweihong1990@hotmail.com

发件人： Weber Zhang<mailto:notifications@github.com>
发送时间： 2017-06-19 10:20
收件人： xindoo/ershoufang<mailto:ershoufang@noreply.github.com>
抄送： Weihong Xu<mailto:xuweihong1990@hotmail.com>; Author<mailto:author@noreply.github.com>
主题： Re: [xindoo/ershoufang] 还有redict问题 (#1)

数据爬取是没问题的，但有时候会被链家ban，会redirect到验证码的页面。

**Comment by xindoo** [comment]
链家的redirect 验证码破解只能通过代理了，没有其他好办法了
